///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PBus_Prj.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The New_CreateEmployee recording.
    /// </summary>
    [TestModule("c03f5ed7-b5c1-47ab-aa06-48f9be1cf9ae", ModuleType.Recording, 1)]
    public partial class New_CreateEmployee : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PBus_Prj.PBus_PrjRepository repository.
        /// </summary>
        public static global::PBus_Prj.PBus_PrjRepository repo = global::PBus_Prj.PBus_PrjRepository.Instance;

        static New_CreateEmployee instance = new New_CreateEmployee();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public New_CreateEmployee()
        {
            varFirstName = "Sri";
            varSecondName = "Ram";
            varSocialSecurity = "017349038";
            varAddress = "49 West Washington Street";
            varCity = "Needham";
            varZipCode = "02193-";
            varPhone = "(617) 555-3985";
            varStartDate = "06272024";
            varTerminationDate = "07272024";
            varBOD = "12271992";
            varSalary = "46700";
            varCity_Validate = "Need";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static New_CreateEmployee Instance
        {
            get { return instance; }
        }

#region Variables

        string _varFirstName;

        /// <summary>
        /// Gets or sets the value of variable varFirstName.
        /// </summary>
        [TestVariable("50065e32-ed29-4784-806b-a68493988e72")]
        public string varFirstName
        {
            get { return _varFirstName; }
            set { _varFirstName = value; }
        }

        string _varSecondName;

        /// <summary>
        /// Gets or sets the value of variable varSecondName.
        /// </summary>
        [TestVariable("388d6dfb-4abb-48bc-bf76-a312cde85a78")]
        public string varSecondName
        {
            get { return _varSecondName; }
            set { _varSecondName = value; }
        }

        string _varSocialSecurity;

        /// <summary>
        /// Gets or sets the value of variable varSocialSecurity.
        /// </summary>
        [TestVariable("6e36c8a5-26f3-4b81-b1a2-1757b94b27ae")]
        public string varSocialSecurity
        {
            get { return _varSocialSecurity; }
            set { _varSocialSecurity = value; }
        }

        string _varAddress;

        /// <summary>
        /// Gets or sets the value of variable varAddress.
        /// </summary>
        [TestVariable("dd6dba36-8318-43d3-b5b2-447513980d42")]
        public string varAddress
        {
            get { return _varAddress; }
            set { _varAddress = value; }
        }

        string _varCity;

        /// <summary>
        /// Gets or sets the value of variable varCity.
        /// </summary>
        [TestVariable("3c1cb489-2838-4eb9-8e20-1c2ed399ef65")]
        public string varCity
        {
            get { return _varCity; }
            set { _varCity = value; }
        }

        string _varZipCode;

        /// <summary>
        /// Gets or sets the value of variable varZipCode.
        /// </summary>
        [TestVariable("c6eba0ae-9a6d-4d23-93fb-70e3c48d2ca2")]
        public string varZipCode
        {
            get { return _varZipCode; }
            set { _varZipCode = value; }
        }

        string _varPhone;

        /// <summary>
        /// Gets or sets the value of variable varPhone.
        /// </summary>
        [TestVariable("e6b43be0-d88d-4111-aa56-2aed78a1ee80")]
        public string varPhone
        {
            get { return _varPhone; }
            set { _varPhone = value; }
        }

        string _varStartDate;

        /// <summary>
        /// Gets or sets the value of variable varStartDate.
        /// </summary>
        [TestVariable("47973301-1074-491e-a485-17636956de25")]
        public string varStartDate
        {
            get { return _varStartDate; }
            set { _varStartDate = value; }
        }

        string _varTerminationDate;

        /// <summary>
        /// Gets or sets the value of variable varTerminationDate.
        /// </summary>
        [TestVariable("a076def3-73d0-4c99-8dcc-036074e258f6")]
        public string varTerminationDate
        {
            get { return _varTerminationDate; }
            set { _varTerminationDate = value; }
        }

        string _varBOD;

        /// <summary>
        /// Gets or sets the value of variable varBOD.
        /// </summary>
        [TestVariable("27553848-fd88-4e36-9c17-dcd7c1d09257")]
        public string varBOD
        {
            get { return _varBOD; }
            set { _varBOD = value; }
        }

        string _varSalary;

        /// <summary>
        /// Gets or sets the value of variable varSalary.
        /// </summary>
        [TestVariable("e7ed00d8-4b3f-4097-aed5-9c04b9e932f0")]
        public string varSalary
        {
            get { return _varSalary; }
            set { _varSalary = value; }
        }

        string _varCity_Validate;

        /// <summary>
        /// Gets or sets the value of variable varCity_Validate.
        /// </summary>
        [TestVariable("cdfd8232-d0bf-45f0-9c42-bc21d0918b24")]
        public string varCity_Validate
        {
            get { return _varCity_Validate; }
            set { _varCity_Validate = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.Element20001' at 213;36.", repo.PowerBuilderUltimateSuiteSampleAppli.Element20001Info, new RecordItemIndex(0));
            repo.PowerBuilderUltimateSuiteSampleAppli.Element20001.Click("213;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.Text25' at 23;5.", repo.PowerBuilderUltimateSuiteSampleAppli.Text25Info, new RecordItemIndex(1));
            repo.PowerBuilderUltimateSuiteSampleAppli.Text25.Click("23;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varFirstName' with focus on 'PowerBuilderUltimateSuiteSampleAppli.Text25'.", repo.PowerBuilderUltimateSuiteSampleAppli.Text25Info, new RecordItemIndex(2));
            repo.PowerBuilderUltimateSuiteSampleAppli.Text25.PressKeys(varFirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varFirstName) on item 'PowerBuilderUltimateSuiteSampleAppli.Text25'.", repo.PowerBuilderUltimateSuiteSampleAppli.Text25Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.PowerBuilderUltimateSuiteSampleAppli.Text25Info, "Text", varFirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.EmpLname' at 18;2.", repo.PowerBuilderUltimateSuiteSampleAppli.EmpLnameInfo, new RecordItemIndex(4));
            repo.PowerBuilderUltimateSuiteSampleAppli.EmpLname.Click("18;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varSecondName' with focus on 'PowerBuilderUltimateSuiteSampleAppli.Text25'.", repo.PowerBuilderUltimateSuiteSampleAppli.Text25Info, new RecordItemIndex(5));
            repo.PowerBuilderUltimateSuiteSampleAppli.Text25.PressKeys(varSecondName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varSecondName) on item 'PowerBuilderUltimateSuiteSampleAppli.Text25'.", repo.PowerBuilderUltimateSuiteSampleAppli.Text25Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.PowerBuilderUltimateSuiteSampleAppli.Text25Info, "Text", varSecondName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.ListItem' at 138;3.", repo.PowerBuilderUltimateSuiteSampleAppli.ListItemInfo, new RecordItemIndex(7));
            repo.PowerBuilderUltimateSuiteSampleAppli.ListItem.Click("138;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PbusSample' at 47;29.", repo.PbusSample.SelfInfo, new RecordItemIndex(8));
            repo.PbusSample.Self.Click("47;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.RD' at 207;7.", repo.PowerBuilderUltimateSuiteSampleAppli.RDInfo, new RecordItemIndex(9));
            repo.PowerBuilderUltimateSuiteSampleAppli.RD.Click("207;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PbusSample' at 34;30.", repo.PbusSample.SelfInfo, new RecordItemIndex(10));
            repo.PbusSample.Self.Click("34;30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.ComboBoxSex' at 209;6.", repo.PowerBuilderUltimateSuiteSampleAppli.ComboBoxSexInfo, new RecordItemIndex(11));
            repo.PowerBuilderUltimateSuiteSampleAppli.ComboBoxSex.Click("209;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PbusSample' at 20;8.", repo.PbusSample.SelfInfo, new RecordItemIndex(12));
            repo.PbusSample.Self.Click("20;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.SocialSecurity' at 46;4.", repo.PowerBuilderUltimateSuiteSampleAppli.SocialSecurityInfo, new RecordItemIndex(13));
            repo.PowerBuilderUltimateSuiteSampleAppli.SocialSecurity.Click("46;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varSocialSecurity' with focus on 'PowerBuilderUltimateSuiteSampleAppli'.", repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo, new RecordItemIndex(14));
            repo.PowerBuilderUltimateSuiteSampleAppli.Self.EnsureVisible();
            Keyboard.Press(varSocialSecurity);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.Street' at 149;9.", repo.PowerBuilderUltimateSuiteSampleAppli.StreetInfo, new RecordItemIndex(15));
            repo.PowerBuilderUltimateSuiteSampleAppli.Street.Click("149;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varAddress' with focus on 'PowerBuilderUltimateSuiteSampleAppli'.", repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo, new RecordItemIndex(16));
            repo.PowerBuilderUltimateSuiteSampleAppli.Self.EnsureVisible();
            Keyboard.Press(varAddress);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varAddress) on item 'PowerBuilderUltimateSuiteSampleAppli.Street'.", repo.PowerBuilderUltimateSuiteSampleAppli.StreetInfo, new RecordItemIndex(17));
            //Validate.AttributeEqual(repo.PowerBuilderUltimateSuiteSampleAppli.StreetInfo, "Text", varAddress);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.City' at 128;3.", repo.PowerBuilderUltimateSuiteSampleAppli.CityInfo, new RecordItemIndex(18));
            repo.PowerBuilderUltimateSuiteSampleAppli.City.Click("128;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varCity' with focus on 'PowerBuilderUltimateSuiteSampleAppli'.", repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo, new RecordItemIndex(19));
            repo.PowerBuilderUltimateSuiteSampleAppli.Self.EnsureVisible();
            Keyboard.Press(varCity);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varCity_Validate) on item 'PowerBuilderUltimateSuiteSampleAppli.City'.", repo.PowerBuilderUltimateSuiteSampleAppli.CityInfo, new RecordItemIndex(20));
            //Validate.AttributeEqual(repo.PowerBuilderUltimateSuiteSampleAppli.CityInfo, "Text", varCity_Validate);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'PowerBuilderUltimateSuiteSampleAppli.City' and assigning its value to variable 'varCity'.", repo.PowerBuilderUltimateSuiteSampleAppli.CityInfo, new RecordItemIndex(21));
            varCity = repo.PowerBuilderUltimateSuiteSampleAppli.City.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.ListItemAB' at 40;5.", repo.PowerBuilderUltimateSuiteSampleAppli.ListItemABInfo, new RecordItemIndex(22));
            repo.PowerBuilderUltimateSuiteSampleAppli.ListItemAB.Click("40;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PbusSample' at 21;31.", repo.PbusSample.SelfInfo, new RecordItemIndex(23));
            repo.PbusSample.Self.Click("21;31");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.ZipCode' at 39;5.", repo.PowerBuilderUltimateSuiteSampleAppli.ZipCodeInfo, new RecordItemIndex(24));
            repo.PowerBuilderUltimateSuiteSampleAppli.ZipCode.Click("39;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varZipCode' with focus on 'PowerBuilderUltimateSuiteSampleAppli'.", repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo, new RecordItemIndex(25));
            repo.PowerBuilderUltimateSuiteSampleAppli.Self.EnsureVisible();
            Keyboard.Press(varZipCode);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.Phone' at 61;8.", repo.PowerBuilderUltimateSuiteSampleAppli.PhoneInfo, new RecordItemIndex(26));
            repo.PowerBuilderUltimateSuiteSampleAppli.Phone.Click("61;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varPhone' with focus on 'PowerBuilderUltimateSuiteSampleAppli'.", repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo, new RecordItemIndex(27));
            repo.PowerBuilderUltimateSuiteSampleAppli.Self.EnsureVisible();
            Keyboard.Press(varPhone);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.StartDate' at 9;6.", repo.PowerBuilderUltimateSuiteSampleAppli.StartDateInfo, new RecordItemIndex(28));
            repo.PowerBuilderUltimateSuiteSampleAppli.StartDate.Click("9;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varStartDate' with focus on 'PowerBuilderUltimateSuiteSampleAppli'.", repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo, new RecordItemIndex(29));
            repo.PowerBuilderUltimateSuiteSampleAppli.Self.EnsureVisible();
            Keyboard.Press(varStartDate);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.TerminationDate' at 7;9.", repo.PowerBuilderUltimateSuiteSampleAppli.TerminationDateInfo, new RecordItemIndex(30));
            //repo.PowerBuilderUltimateSuiteSampleAppli.TerminationDate.Click("7;9");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varTerminationDate' with focus on 'PowerBuilderUltimateSuiteSampleAppli'.", repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo, new RecordItemIndex(31));
            //repo.PowerBuilderUltimateSuiteSampleAppli.Self.EnsureVisible();
            //Keyboard.Press(varTerminationDate);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.DateOfBirth' at 7;9.", repo.PowerBuilderUltimateSuiteSampleAppli.DateOfBirthInfo, new RecordItemIndex(32));
            repo.PowerBuilderUltimateSuiteSampleAppli.DateOfBirth.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varBOD' with focus on 'PowerBuilderUltimateSuiteSampleAppli'.", repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo, new RecordItemIndex(33));
            repo.PowerBuilderUltimateSuiteSampleAppli.Self.EnsureVisible();
            Keyboard.Press(varBOD);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.Salary' at 53;7.", repo.PowerBuilderUltimateSuiteSampleAppli.SalaryInfo, new RecordItemIndex(34));
            repo.PowerBuilderUltimateSuiteSampleAppli.Salary.Click("53;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varSalary' with focus on 'PowerBuilderUltimateSuiteSampleAppli'.", repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo, new RecordItemIndex(35));
            repo.PowerBuilderUltimateSuiteSampleAppli.Self.EnsureVisible();
            Keyboard.Press(varSalary);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.Element1005' at 17;7.", repo.PowerBuilderUltimateSuiteSampleAppli.Element1005Info, new RecordItemIndex(36));
            repo.PowerBuilderUltimateSuiteSampleAppli.Element1005.Click("17;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.Element1004' at 12;21.", repo.PowerBuilderUltimateSuiteSampleAppli.Element1004Info, new RecordItemIndex(37));
            repo.PowerBuilderUltimateSuiteSampleAppli.Element1004.Click("12;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.Element20001' at 41;36.", repo.PowerBuilderUltimateSuiteSampleAppli.Element20001Info, new RecordItemIndex(38));
            repo.PowerBuilderUltimateSuiteSampleAppli.Element20001.Click("41;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.Element20001' at 34;15.", repo.PowerBuilderUltimateSuiteSampleAppli.Element20001Info, new RecordItemIndex(39));
            repo.PowerBuilderUltimateSuiteSampleAppli.Element20001.Click("34;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'PowerBuilderUltimateSuiteSampleAppli.Text25'.", repo.PowerBuilderUltimateSuiteSampleAppli.Text25Info, new RecordItemIndex(40));
            Validate.NotExists(repo.PowerBuilderUltimateSuiteSampleAppli.Text25Info);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PowerBuilderUltimateSuiteSampleAppli.Element20001' at 36;56.", repo.PowerBuilderUltimateSuiteSampleAppli.Element20001Info, new RecordItemIndex(41));
            //repo.PowerBuilderUltimateSuiteSampleAppli.Element20001.Click("36;56");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 1s to not exist. Associated repository item: 'PowerBuilderUltimateSuiteSampleAppli'", repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo, new ActionTimeout(1000), new RecordItemIndex(42));
            //repo.PowerBuilderUltimateSuiteSampleAppli.SelfInfo.WaitForNotExists(1000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
